---
title: "BFV"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BFV}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Load libraries that will be used.
```{r setup}
library(HomomorphicEncryption)
library(polynom)
```

Set some parameters.
```{r params}
d  =   4
n  =   2^d
p  =   (n/2)-1
q  = 874
pm = GenPolyMod(n)
```

Create the secret key and the polynomials a and e, which will go into the public key
```{r}
# create secret key
s = polynomial( coef=c(-1, -1, 0, 0, -1, 1, 0, 0, 0, 1, 0, -1, -1, 1, -1, 0 ) )

# define a
a = polynomial( coef=c(136, 239, 313, 241, 615, 37, 233, 408, 570, 8, 356, 132, 558, 110, 706, 327) )

# define the error
e = polynomial( coef=c(2, 7, -2, -2, 8, 1, 0, 3, 6, -2, -2, 6, 3, 4, -3) )
```

Generate the public key.
```{r}
# generate the public key
pk0 = GenPubKey0(a, s, e, pm, q)
pk1 = GenPubKey1(a)
```

Create a polynomial message
```{r}
# create a message
m = polynomial( coef=c(1, 1, 1) )
```

Create polynomials for the encryption
```{r}
# polynomials for encryption
e1 = polynomial( coef=c( 6, -1,  3,  3, 9,  0, 3, -3, -5, 0, -7, 1, -5, 0, 4, 1) )
e2 = polynomial( coef=c(-5, -3, -1, -1, 1, -7, 2,  0,  2, 0, -2, 6,  0, 1, 0, 1) )
u  = polynomial( coef=c( 1, -1,  1, -1, 1,  1, 0,  0, -1, 0,  1, 1,  0, 1) )
```

Generate the ciphertext
```{r}
ct0 = EncryptPoly0(m, pk0, u, e1, p, pm, q)
ct1 = EncryptPoly1(   pk1, u, e2,    pm, q)
```

Decrypt
```{r}
decrypt = (ct1 * s) + ct0
decrypt = decrypt %% pm
decrypt = CoefMod(decrypt, q)

# rescale
decrypt = decrypt * p/q
```

Round (remove the error) then mod p
```{r}
# round then mod t
decrypt = CoefMod(round(decrypt), p)
print(decrypt)
```
